#!/usr/bin/env bash

# Python specific
alias ipy='ipython'
alias py='python'
alias webdir='python -m SimpleHTTPServer'
# Django specific
alias dshell='python manage.py shell'
alias dserve='python manage.py runserver 0.0.0.0:9999 '
alias dmigratelist='python manage.py migrate --list'
alias dmigrate='python manage.py migrate '
alias dschema='python manage.py schemamigration '
alias dmm='python manage.py makemessages -a'
alias dcm='python manage.py compilemessages'
#Common
alias ip_external='curl http://api.externalip.net/ip/'
if [ -f ~/.bash_profile ]; then
	alias reload='source ~/.bash_profile'
fi
if [ -f ~/.bashrc ]; then
	alias reload='source ~/.bashrc'
fi
alias vi='vim'
alias www='cd ~/.virtualenvs/www/; ll;'
alias mkdir='mkdir -p'
alias site='cd ~/.virtualenvs/django151/lib/python2.7/site-packages/'
alias pm='python manage.py'
alias mysql.start='sudo /usr/local/mysql/support-files/mysql.server start'
alias mysql.stop='sudo /usr/local/mysql/support-files/mysql.server stop'
alias mysql.restart='mysql.stop;mysql.start;'
alias find0='find . -type f -print0 | xargs -0 grep'
