#!/usr/bin/env bash

# Python specific
alias ipy='ipython'
alias py='python'
alias py2.6='python2.6'
alias webdir='python -m SimpleHTTPServer'
# Django specific
alias dshell='python manage.py shell'
alias dserve='python manage.py runserver 0.0.0.0:9999 '
alias dmigratelist='python manage.py migrate --list'
alias dmigrate='python manage.py migrate '
alias dschema='python manage.py schemamigration '
alias dmm='python manage.py makemessages -a'
alias dcm='python manage.py compilemessages'
#Common
alias ip='curl ifconfig.me'
if [ -f ~/.bash_profile ]; then
	alias reload='source ~/.bash_profile'
fi
if [ -f ~/.bashrc ]; then
	alias reload='source ~/.bashrc'
fi
alias vi='vim'
alias www='cd ~/.virtualenvs/www/; ll;'
alias mkdir='mkdir -p'


